Region: us-east-1
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: c5.4xlarge
  Networking:
    SubnetId: subnet-07606ee7f2b12e512
  Ssh:
    KeyName: michael-keypair
  LocalStorage:
    RootVolume:
      Size: 1024
  CustomActions:
      OnNodeConfigured:
        Script: s3://optimum-neuron/install_neuron.sh
  Iam:
    InstanceRole: arn:aws:iam::754289655784:role/optimum-neuron-dev
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: compute1
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 1024
          EphemeralVolume:
            MountDir: /local_storage
      ComputeResources:
        - Efa:
            Enabled: true
          InstanceType: trn1.32xlarge
          MaxCount: 8
          MinCount: 0
          Name: queue1-i1
      Networking:
        SubnetIds:
          - subnet-0909502214c677c17
        PlacementGroup:
          Enabled: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://optimum-neuron/install_neuron.sh
      Iam:
        InstanceRole: arn:aws:iam::754289655784:role/optimum-neuron-dev
  SlurmSettings:
    ScaledownIdletime: 180
SharedStorage:
- FsxLustreSettings:
    DeploymentType: SCRATCH_2
    StorageCapacity: 1200
  MountDir: /fsx
  Name: pclusterfsx
  StorageType: FsxLustre

