name: Prepare virtual environment
description: prepare virtual environment to install pyhton packages
runs:
    using: "composite"
    steps:
      - name: Prepare virtual environment
        shell: bash
        run: |
          sudo apt install python3-venv python3-dev -y
          python3 -m venv aws_neuron_venv_pytorch
          source aws_neuron_venv_pytorch/bin/activate
          python -m pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com
          python -m pip install -U pip
          python -m pip install --upgrade setuptools==69.5.1
          python -m pip install hf_transfer
          # Install torch and torchvision for CPU: this avoids having to install CUDA related dependencies, that use a lot
          # of disk space. Note dependencies should be updated when we bump the PyTorch version.
          python -m pip install torch==2.7.1 torchvision~=0.22 --index-url https://download.pytorch.org/whl/cpu
