name: Setup virtual environment
description: Prepare virtual environment and install optimum-neuron
inputs:
  torch_version:
    description: 'The pytorch version to be installed'
    required: true
    default: '2.8.0'
  torchvision_version:
    description: 'The torchvision version to be installed'
    required: true
    default: '0.23.0'
runs:
    using: "composite"
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.27
      - name: Prepare venv and install Optimum Neuron python package
        shell: bash
        run: |
          uv venv --python 3.11 aws_neuron_venv_pytorch
          source aws_neuron_venv_pytorch/bin/activate
          uv pip install .[neuronx,tests]
