version: '3.7'

services:
  tgi-1:
    image: neuronx-tgi:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MODEL_ID=${MODEL_ID}
      - HF_AUTO_CAST_TYPE=${HF_AUTO_CAST_TYPE}
      - HF_NUM_CORES=32
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE}
      - MAX_INPUT_LENGTH=${MAX_INPUT_LENGTH}
      - MAX_TOTAL_TOKENS=${MAX_TOTAL_TOKENS}
      - MAX_CONCURRENT_REQUESTS=512
    volumes:
      - $PWD:/data
    devices:
      - "/dev/neuron0"
      - "/dev/neuron1"
      - "/dev/neuron2"
      - "/dev/neuron3"
      - "/dev/neuron4"
      - "/dev/neuron5"
      - "/dev/neuron6"
      - "/dev/neuron7"
      - "/dev/neuron8"
      - "/dev/neuron9"
      - "/dev/neuron10"
      - "/dev/neuron11"
      - "/dev/neuron12"
      - "/dev/neuron13"
      - "/dev/neuron14"
      - "/dev/neuron15"
      