name: Install Neuronx SDK
description: install system and python packages for an AWS Neuronx SDK version
runs:
    using: "composite"
    steps:
      - name: Set APT_CACHE_DIR env variable
        shell: bash
        run: |
          echo "APT_CACHE_DIR=/mnt/hf_cache/apt-${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Wait for cache to be ready
        uses: lewagon/wait-on-check-action@v1.5.0
        with:
          ref: ${{ github.ref }}
          check-name: "Setup Neuronx system cache"
          repo-token: ${{ github.token }}
          wait-interval: 10
      - name: Install Neuronx system packages
        shell: bash
        run: |
          sudo dpkg -i ${APT_CACHE_DIR}/*.deb
          export PATH=/opt/aws/neuron/bin:$PATH
          dpkg -l | grep neuron
      - name: Display driver version
        shell: bash
        run: |
          apt show aws-neuronx-dkms
