version: '3.7'

services:
  vllm-1:
    image: optimum-neuron-vllm:latest
    ports:
      - "8081:8081"
    environment:
      - SM_VLLM_PORT=8081
      - SM_VLLM_MODEL=${MODEL_ID}
      - SM_VLLM_TENSOR_PARALLEL_SIZE=8
      - SM_VLLM_MAX_NUM_SEQS=${MAX_BATCH_SIZE}
      - SM_VLLM_MAX_MODEL_LEN=${MAX_TOTAL_TOKENS}
      - HF_TOKEN=${HF_TOKEN}
    devices:
      - "/dev/neuron0"
      - "/dev/neuron1"
      - "/dev/neuron2"
      - "/dev/neuron3"

  vllm-2:
    image: optimum-neuron-vllm:latest
    ports:
      - "8082:8082"
    environment:
      - SM_VLLM_PORT=8082
      - SM_VLLM_MODEL=${MODEL_ID}
      - SM_VLLM_TENSOR_PARALLEL_SIZE=8
      - SM_VLLM_MAX_NUM_SEQS=${MAX_BATCH_SIZE}
      - SM_VLLM_MAX_MODEL_LEN=${MAX_TOTAL_TOKENS}
      - HF_TOKEN=${HF_TOKEN}
    devices:
      - "/dev/neuron4"
      - "/dev/neuron5"
      - "/dev/neuron6"
      - "/dev/neuron7"

  vllm-3:
    image: optimum-neuron-vllm:latest
    ports:
      - "8083:8083"
    environment:
      - SM_VLLM_PORT=8083
      - SM_VLLM_MODEL=${MODEL_ID}
      - SM_VLLM_TENSOR_PARALLEL_SIZE=8
      - SM_VLLM_MAX_NUM_SEQS=${MAX_BATCH_SIZE}
      - SM_VLLM_MAX_MODEL_LEN=${MAX_TOTAL_TOKENS}
      - HF_TOKEN=${HF_TOKEN}
    devices:
      - "/dev/neuron8"
      - "/dev/neuron9"
      - "/dev/neuron10"
      - "/dev/neuron11"

  loadbalancer:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx-dp3.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vllm-1
      - vllm-2
      - vllm-3
    deploy:
      placement:
        constraints: [node.role == manager]
