name: Build and push optimum-neuron-vllm docker image to ghcr.io

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on:
      group: aws-general-8-plus
    permissions:
      contents: write
      packages: write
    steps:
      -
        name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      -
        name: Extract version
        run: |
          sudo apt-get install -y gawk
          export ON_VERSION=$(make version)
          echo "ON_VERSION=${ON_VERSION}">> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f  # v3
      -
        name: Login to ghcr.io
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8  # v6
        with:
          context: .
          file: docker/vllm/Dockerfile
          push: true
          tags: ghcr.io/huggingface/optimum-neuron-vllm:${{ env.ON_VERSION }}, ghcr.io/huggingface/optimum-neuron-vllm:latest
