name: Build and push optimum-neuron-vllm docker image to ghcr.io

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on:
      group: aws-general-8-plus
    permissions:
      contents: write
      packages: write
    steps:
      -
        name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      -
        name: Extract version
        run: |
          sudo apt-get install -y gawk
          export ON_VERSION=$(make version)
          echo "ON_VERSION=${ON_VERSION}">> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd  # v4.0.0
      -
        name: Login to ghcr.io
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121  # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121  # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f  # v7.1.0
        with:
          context: .
          file: docker/vllm/Dockerfile
          push: true
          tags: ghcr.io/huggingface/optimum-neuron-vllm:${{ env.ON_VERSION }}, ghcr.io/huggingface/optimum-neuron-vllm:latest
