name: Optimum neuron SD inference cache builder

on:
  workflow_dispatch:
  schedule:
    # Schedule the workflow to run every Saturday at midnight UTC
    - cron: '0 0 * * 6'
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  cache:
    name: Create optimum-neuron inference cache
    runs-on:
      group: aws-inf2-8xlarge
    env:
      AWS_REGION: us-east-1
      HF_HUB_ENABLE_HF_TRANSFER: 1
    strategy:
      fail-fast: false
      matrix:
        config: [
          pixart-alpha-xl-512x512,
          pixart-sigma-xl-512x512,
          sdxl-turbo,
          stable-diffusion-2-1,
          stable-diffusion-v1-5,
          stable-diffusion-xl-base-1.0,
          stable-diffusion-xl-refiner-1.0,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Neuronx runtime
        uses: ./.github/actions/install_neuronx_runtime
      - name: Prepare virtual environment
        uses: ./.github/actions/prepare_venv
      - name: Install optimum-neuron
        uses: ./.github/actions/install_optimum_neuron
      - name: Create cache for ${{matrix.config}} models
        run: |
          source aws_neuron_venv_pytorch/bin/activate
          config_prefix_url=https://huggingface.co/aws-neuron/optimum-neuron-cache/raw/main/inference-cache-config
          HF_TOKEN=${{secrets.HF_TOKEN_OPTIMUM_NEURON_CACHE}} \
            python tools/auto_fill_inference_cache.py --config_file ${config_prefix_url}/${{matrix.config}}.json
