name: Optimum Neuron - Test optimum.neuron.distributed on Trainium

on:
  push:
    branches: [ main ]
    paths:
      - "setup.py"
      - "optimum/neuron/distributed/**.py"
      - ".github/workflows/test_trainium_distributed.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "setup.py"
      - "optimum/neuron/distributed/**.py"
      -  ".github/workflows/test_trainium_distributed.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  optimum-neuron-tests:
    name: Run distributed tests on Trainium 1
    runs-on:
      group: aws-trn1-32xlarge
    steps:
      - name: Install Neuron runtime
        run: |
          . /etc/os-release
          sudo tee /etc/apt/sources.list.d/neuron.list > /dev/null <<EOF
          deb https://apt.repos.neuron.amazonaws.com ${VERSION_CODENAME} main
          EOF
          wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | sudo apt-key add -
          sudo apt-get update -y
          sudo apt-get install aws-neuronx-tools=2.19.0.0 aws-neuronx-runtime-lib=2.22.14.0-6e27b8d5b aws-neuronx-collectives=2.22.26.0-17a033bc8  -y
          export PATH=/opt/aws/neuron/bin:$PATH
      - name: Install cv2 dependencies
        run: |
          sudo apt-get install ffmpeg libsm6 libxext6  -y
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PATH
        run: echo "/home/ubuntu/.local/bin" >> $GITHUB_PATH
      - name: Install python dependencies
        run: |
          sudo apt install python3-venv python3-dev -y
          python3 -m venv aws_neuron_venv_pytorch
          source aws_neuron_venv_pytorch/bin/activate
          python -m pip install -U pip
          pip install --upgrade setuptools==69.5.1
          python -m pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com
          python -m pip install .[neuronx,tests]
      - name: Collect tests on Neuron Cores
        run: |
          source aws_neuron_venv_pytorch/bin/activate
          HF_TOKEN=${{ secrets.HF_TOKEN_OPTIMUM_NEURON_CI }} pytest -m "is_trainium_test" tests/distributed/ --collect-only
      - name: Run tests on Neuron Cores
        run: |
          source aws_neuron_venv_pytorch/bin/activate
          HF_TOKEN=${{ secrets.HF_TOKEN_OPTIMUM_NEURON_CI }} pytest -m "is_trainium_test" tests/distributed/ -v --durations=0 -x

