name: Optimum neuron / Test TGI on INF2

on:
  push:
    branches: [ main ]
    paths:
      - "setup.py"
      - "optimum/**.py"
      - "text-generation-inference/**"
  pull_request:
    branches: [ main ]
    paths:
      - "setup.py"
      - "optimum/**.py"
      - "text-generation-inference/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  do-the-job:
    name: Run TGI tests
    runs-on: [self-hosted, 1-aws-inf2, 32-cpu, ci] # run the job on the newly created runner
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install python and create venv
        run: |
          sudo apt install python3.8-venv -y
          python3 -m venv aws_neuron_venv_pytorch
          source aws_neuron_venv_pytorch/bin/activate
          python -m pip install -U pip
          python -m pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com
      - name: Run TGI server python tests
        run: |
          source aws_neuron_venv_pytorch/bin/activate
          HF_TOKEN=${{ secrets.HF_TOKEN_OPTIMUM_NEURON_CI }} make tgi_test
