name: Optimum neuron / Test INF2 full export

on:
  push:
    branches: [ main ]
    paths:
      - "optimum/exporters/neuron/*.py"
      - ".github/workflows/test_inf2_full_export.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "optimum/exporters/neuron/*.py"
      - ".github/workflows/test_inf2_full_export.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  do-the-job:
    name: Run INF2 full export tests
    runs-on:
      group: aws-inf2-8xlarge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Neuronx runtime
        uses: ./.github/actions/install_neuronx_runtime
      - name: Prepare virtual environment
        uses: ./.github/actions/prepare_venv
      - name: Install optimum-neuron
        uses: ./.github/actions/install_optimum_neuron
      - name: Install cv2 dependencies
        run: |
          sudo apt-get install python3-opencv -y
      - name: Run exporters tests
        run: |
          source aws_neuron_venv_pytorch/bin/activate
          HF_TOKEN=${{ secrets.HF_TOKEN_OPTIMUM_NEURON_CI }} pytest -m is_inferentia_test tests/exporters
