name: Optimum Neuron - Test optimum.neuron.distributed on Trainium

on:
  push:
    branches: [ main ]
    paths:
      - "setup.py"
      - "optimum/neuron/distributed/**.py"
      - ".github/workflows/test_trainium_distributed.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "setup.py"
      - "optimum/neuron/distributed/**.py"
      -  ".github/workflows/test_trainium_distributed.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  optimum-neuron-tests:
    name: Run distributed tests on Trainium 1
    runs-on:
      group: aws-trn1-32xlarge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Neuronx runtime
        uses: ./.github/actions/install_neuronx_runtime
      - name: Install cv2 dependencies
        run: |
          sudo apt-get install ffmpeg libsm6 libxext6  -y
      - name: Prepare virtual environment
        uses: ./.github/actions/prepare_venv
      - name: Install optimum-neuron
        uses: ./.github/actions/install_optimum_neuron
      - name: Setup PATH
        run: echo "/home/ubuntu/.local/bin" >> $GITHUB_PATH
      - name: Collect tests on Neuron Cores
        run: |
          source aws_neuron_venv_pytorch/bin/activate
          HF_TOKEN=${{ secrets.HF_TOKEN_OPTIMUM_NEURON_CI }} pytest -m "is_trainium_test" tests/distributed/ --collect-only
      - name: Run tests on Neuron Cores
        run: |
          source aws_neuron_venv_pytorch/bin/activate
          HF_TOKEN=${{ secrets.HF_TOKEN_OPTIMUM_NEURON_CI }} pytest -m "is_trainium_test" tests/distributed/ -v --durations=0 -x

