name: Optimum Neuron - Test optimum.neuron.distributed on Trainium

on:
  push:
    branches: [ main ]
    paths:
      - "setup.py"
      - "optimum/neuron/distributed/**.py"
  pull_request:
    branches: [ main ]
    paths:
      - "setup.py"
      - "optimum/neuron/distributed/**.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  optimum-neuron-tests:
    runs-on: [self-hosted, 16-aws-trn, 128-cpu, ci]
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Check AMI
        run: dpkg -l | grep neuron
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PATH
        run: echo "/home/ubuntu/.local/bin" >> $GITHUB_PATH
      - name: Set pip repository pointing to the Neuron repository
        run: pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com
      - name: Install Python dependencies
        run: pip install .[tests,neuronx]
      - name: Run tests on Neuron cores
        run: |
          HF_TOKEN=${{ secrets.HF_TOKEN_OPTIMUM_NEURON_CI }} pytest -m "is_trainium_test" tests/distributed/ -v --durations=0 -x --ignore tests/distributed/test_training.py

